### ISSUE TITLE
TM packets, field "absolute time", size is 2 bytes - is it correct?

### ISSUE THREAD

**Issue by kmarinushkin** [visionspacetec/Prust#6]
Hello, my name is Kirill! I work with TUDSaT team on a PUS implementation for our CubeSat. You might remember me from OSCSW 2020.
We start using Prust as a reference for our testing. Our test-cases revealed a contradiction between our implementation and Prust. We want to share with you our observations in a series of Github "issues". These are not bug-reports, but rather proposals for discussions, to figure out, what it the right way to do PUS.

---

In our [test-case](https://gitlab.com/tudsat-cubesat/communication/librepus/-/merge_requests/10/diffs?commit_id=b1f5063ccb6575cc5dd975532761e9c6f5785e6b#2a6572d8f543c4c359c88f6c700944ad6bcdd4b6_0_25), we try to decode the example TM[1,7] packet from [Prust wiki](https://github.com/visionspacetec/Prust/wiki/How-to-Use-the-Client-Crate).

The issue we faced is in PUS TM packet field "absolute time" (ref. PUS document ECSS-E-ST-70-41C from 15 April 2016, Chapter 7.4.3.1). We did not yet decide, which format we want to use - PUS supports several (ref. Chapter 7.3.10). However, none of them is 2-byte long, as used by Prust, according to the example packet.

Did you find a way to decode absolute time in 2 bytes, or is it a overlook? I would be glad to reduce packet size in this field, so, if you found a way - I would be interested to know, how to achieve it

**Comment by feiteira** [comment]
@SelmanOzleyen please consider using CUC 4,2 (4 bytes seconds, 2 bytes fractions 1/65536)

**Comment by kmarinushkin** [comment]
Hello @feiteira! CUC 4,2 seems very well-packed, nice :) Are you aware of any format, which could be even more size-efficient? 6 bytes per packet just on timestamp still seems a lot to me

**Comment by SelmanOzleyen** [comment]
Hi, It was a temporary dummy field. I checked out CCSDS 301.0-B-4, I think it is important for us to use a standard here.
I will be changing the field from primitive to a struct and reserve 6 bytes for that place but since we don't use time in the software it will stay empty for now.

**Comment by kmarinushkin** [comment]
Thanks @SelmanOzleyen for your reply!

Nice, then we also allocate 6-bytes for time for now. I also looked into CCSDS 301.0-B-4, and i see, that it describes several formats, so, there is still a variety of stadard time formats, to choose from.
When we or you come to time implementation - let's sync again. I think it will help, if our libraries stay compatible to each other.

That pretty much answers my question, you may now close this "issue" whenever it's convenient for you.

**Comment by SelmanOzleyen** [comment]
Ok, I will close this issue. Might open a new one later concerning the values in that field. Thank you for reminding since it is important to be in sync with other softwares.
