### ISSUE TITLE
TM[1,7] unexpected 2 bytes in the end of packet

### ISSUE THREAD

**Issue by kmarinushkin** [visionspacetec/Prust#8]
This finding is related to the following TM[1,7] packet from [wiki page](https://github.com/visionspacetec/Prust/wiki/How-to-Use-the-Client-Crate):

~~~~
The packet recieved (in bytes):
[8, 42, 192, 0, 0, 14, 32, 1, 7, 0, 0, 0, 42, 0, 0, 24, 42, 192, 0, 0, 0]
~~~~

it looks to me, that the last 2 bytes `0, 0` shouldn't be there. From the printed parsed structure, i see, that maybe those bytes represent the field `packet_error_control: 0`. However, from what i can see in PUS documentation, there is no such field in TM[1,7].

What do you think?

**Comment by SelmanOzleyen** [comment]
Hi Kirill;
First of all thanks for the contribution again.
packet error control is an optional 2 bytes field. This is a stub field at this point filled with 0.
From 7.4.3.2 (PUS-C):
> The packet error control field transports an error detection code that is
> used by the ground system to verify the checksum of the telemetry packet.
> Its optional presence is driven by requirement 7.4.3.2d.
Note: Maybe we can add a conditional compilation features to choose if we want to add that field or not with some macros. For now my priority is to run the tasks from FreeRTOS. But it is good to have some possible enhancements listed.

**Comment by syelman** [comment]
So unless you still don't think that 2 should be there I am closing this issue. Might create a new issue for optional compilation as I said above but that's another topic.

**Comment by kmarinushkin** [comment]
Hello @syelman, yes, thank you for clarification!
Didn't find time to answer you yesterday, but yes, I understand now, it's CRC, missed it previously
